// ===========================================================================
// v0.78 §A1-§A3 — CURRENT-STATE DOCUMENTS, GENERATED.
//
// THE DEFECT THIS FIXES
//
// The packaged v0.77.2 tree shipped `CONTENT_BACKLOG.md` and
// `CURRICULUM_COVERAGE_MATRIX.md` still stamped v0.72.0 and still saying
// "8 of 9 Fractions sections complete, §7.9 incomplete". The code had
// said 9 of 9 since v0.75. Both files carried the line "Generated by
// coverageBacklog() … Not maintained by hand", which was true when they
// were written and became a lie the moment the model moved: nothing
// regenerated them and nothing checked them.
//
// A document that claims to be generated and is not is worse than one
// admitting it is hand-written, because a reader has no reason to doubt
// it. Someone planning content from that backlog would have planned to
// write a section that already existed.
//
// THE FIX HAS TWO HALVES, AND THE SECOND IS THE IMPORTANT ONE
//
//   1. these render functions read the live model, so regenerating is
//      one command;
//   2. `v078StateDocs.test.ts` asserts the bytes on disk equal what
//      these functions produce right now. Staleness is a test failure,
//      not something to be noticed.
//
// Regenerate with:  PRAGATI_EMIT_DOCS=1 npx vitest run v078StateDocs
//
// WHAT THESE DOCUMENTS MUST KEEP SEPARATE
//
// The three truths never collapse into one number:
//   CURRICULUM      what the official book contains;
//   INSTRUCTION     what Pragati has written for it;
//   REVIEW          what an educator has approved and what is published.
// A chapter can be fully represented, entirely unwritten, and correctly
// show zero published lessons — all three at once, all three true.
// ===========================================================================

import {
  coverageMatrix,
} from './coverageMatrix';
// v0.82.3 §3 — state documents made product-wide claims out of a
// deprecated Fractions-only wrapper, so every "current state" sentence
// silently meant Chapter 7.
import {
  reviewReadinessByChapter,
  reviewReadinessSummaryForChapter,
} from './reviewReadiness';
import { AUTHORED_CHAPTERS } from './authoredSections';
import { assessSection } from './instructionalCompleteness';

import { MASTER_RECORDS, classStructureStatus, CLASS_NUMBERS } from './curriculumMasterMap';
import {
  hierarchyTable,
  gapReportTable,
  registryLagParagraph,
  renderProductionBacklogSection,
  renderStructureBacklogDocument,
  renderBooksDocument,
} from './masterMapDocs';

const masterCompleteClasses = () =>
  CLASS_NUMBERS.filter((n) => classStructureStatus(n) === 'complete_at_structure_level').length;

const STAMP = (version: string) =>
  `**Generated** from the live model by \`src/curriculum/stateDocs.ts\` at ` +
  `version ${version}. Do not hand-edit: \`v078StateDocs.test.ts\` compares ` +
  `this file to the model on every run, so an edit here fails the suite and ` +
  `a model change that is not regenerated fails it too.`;

function table(headers: string[], rows: string[][]): string {
  const head = `| ${headers.join(' | ')} |`;
  const rule = `|${headers.map(() => '---').join('|')}|`;
  const body = rows.map((r) => `| ${r.join(' | ')} |`).join('\n');
  return [head, rule, body].join('\n');
}


// ---------------------------------------------------------------------------


/**
 * v0.82.3 §1/§2 — chapter distribution, derived.
 *
 * The matrix said "12 complete instructional drafts, all in Class 6
 * Chapter 7", which stopped being true the moment Number Play was
 * authored — and would have gone on being printed as fact. The
 * breakdown is computed from the authored registry, so a chapter added
 * later appears here without anyone remembering to edit a sentence.
 */
function authoredChapterBreakdown(): Array<{
  title: string;
  complete: number;
  reviewReady: number;
}> {
  return AUTHORED_CHAPTERS.map((c) => {
    const sections = c.sections();
    return {
      title: c.title,
      complete: sections.filter(
        (s) => assessSection(s).level === 'complete_instructional_draft'
      ).length,
      reviewReady: reviewReadinessSummaryForChapter(c.officialChapterId)
        .reviewReady,
    };
  });
}

function breakdownSentence(): string {
  const parts = authoredChapterBreakdown()
    .filter((c) => c.complete > 0)
    .map((c) => `${c.complete} in ${c.title}`);
  const total = authoredChapterBreakdown().reduce((a, c) => a + c.complete, 0);
  return `${total} complete instructional drafts — ${parts.join(', ')}`;
}

export function renderCoverageMatrix(version: string): string {
  const rows = coverageMatrix();
  const rr = reviewReadinessSummaryForChapter(AUTHORED_CHAPTERS[1].officialChapterId);
  const unverified = rows.filter((r) => !r.verified);

  return `# Curriculum Coverage Matrix — Classes 1–12 Mathematics

${STAMP(version)}

---

## The three truths, kept apart

| Truth | Question it answers | Current answer |
|---|---|---|
| Curriculum completeness | Does Pragati represent every official record? | ${masterCompleteClasses()} of 12 classes complete at structure level in the master map; ${MASTER_RECORDS.length} official records represented; none omitted |
| Instructional completeness | Has Pragati written the teaching for those records? | ${breakdownSentence()} |
| Review / publication | Has an educator approved it, and is it published? | ${rows.reduce((a, r) => a + r.educatorReviewed, 0)} reviewed, ${rows.reduce((a, r) => a + r.published, 0)} published |

A class whose structure is not fully known is **not** a class with no
curriculum. Its denominator is UNKNOWN, never zero.

${registryLagParagraph()}

---

## 1. Curriculum completeness

Read from the curriculum master map. One row per source hierarchy: for
Classes 9–12 the CBSE syllabus and the NCERT textbook are separate rows
and neither is folded into the other. A dash means the source does not
define that level; UNKNOWN means it has not been fully read.

${hierarchyTable()}

## 1b. Content gap report — every class, honest denominators

${gapReportTable()}

## 2. Instructional content completeness

${table(
  // v0.82.5 §5 — "Topics: Learn" called Class 6's authored records
  // topics, and they are sections. These counts are per authored
  // RECORD, whatever level the source calls it, so the labels say so.
  // The values are unchanged; only the words were wrong.
  ['Class', 'Student-openable Learn chapters', 'Records with Learn', 'Records with guided practice', 'Records with independent practice', 'Records with reasoning', 'Records with a visual', 'Records with teacher notes', 'Complete drafts'],
  rows.map((r) => [
    r.gradeLabel,
    String(r.chaptersWithLearn),
    String(r.topicsWithLearn),
    String(r.topicsWithGuidedPractice),
    String(r.topicsWithIndependentPractice),
    String(r.topicsWithReasoning),
    String(r.topicsWithVisual),
    String(r.topicsWithTeacherResources),
    String(r.completeInstructionalDrafts),
  ])
)}

## 3. Review and publication

${table(
  ['Class', 'Drafts', 'Educator reviewed', 'Student ready', 'Published'],
  rows.map((r) => [
    r.gradeLabel,
    String(r.drafts),
    String(r.educatorReviewed),
    String(r.studentReady),
    String(r.published),
  ])
)}

### Fractions detail — Class 6, Chapter 7

The per-chapter table below is the cross-chapter source of truth. This
block is kept because it carries Chapter 7's sent / received /
adjudicated counts, which the table does not.

- Complete drafts: **${rr.completeDrafts}**
- Review-ready (blocked on a person): **${rr.reviewReady}**
- Awaiting package preparation (blocked on engineering): **${rr.awaitingPackagePreparation}**
- Sent: **${rr.reviewSent}** · Received: **${rr.reviewReceived}** · Adjudicated: **${rr.reviewAdjudicated}**

${rr.headline}

---

## The five states a section can be in

v0.74 §5 established these, and they stay stated separately because
collapsing any two of them is how a draft starts looking like a lesson.

1. **No instructional content at all** — the official record exists in
   Pragati and nothing has been written for it.
2. **Partial draft** — some of Learn, practice, reasoning or teacher
   notes exists, but not enough to be reviewable.
3. **Complete draft, no review package** — reviewable in substance, but
   an educator cannot yet read it because the package is unbuilt. This
   is engineering work.
4. **Complete draft, review-ready** — blocked on a person, not on us.
5. **Reviewed and published** — the only state a student may see.

Currently, by chapter:

${table(
  ['Chapter', 'Complete drafts', 'Review-ready (state 4)'],
  authoredChapterBreakdown().map((c) => [
    c.title,
    String(c.complete),
    String(c.reviewReady),
  ])
)}

**Total: ${authoredChapterBreakdown().reduce((a, c) => a + c.reviewReady, 0)}**
sections in state 4, **0** in state 3, and **0** in state 5.

The packages stay chapter-scoped — a reviewer receives one chapter — so
this total is a report, not a queue.

---

## Backlog totals mean the verified classes only

The known instructional backlog is the work Pragati can currently see.
It is **not the Classes 1–12 workload**: classes awaiting primary
verification have an unknown denominator, and adding zero for them would
understate the real total by an unknown amount.

---

## Classes awaiting primary verification

${unverified.length === 0 ? 'None.' : unverified.map((r) => `- ${r.gradeLabel}`).join('\n')}

For these classes every count above is unknown, not zero. They are
tracked in \`STRUCTURE_VERIFICATION_BACKLOG.md\`.
`;
}

// ---------------------------------------------------------------------------

export function renderContentBacklog(version: string): string {
  // Read from the same matrix everything else reads, so the backlog and
  // the coverage document cannot disagree about which classes are
  // verified.

  return `# Content Backlog — what is missing, and in what order

${STAMP(version)}

---

${renderProductionBacklogSection()}

${reviewReadinessByChapter()
  .filter((c) => c.rows.length > 0)
  .map((c) => {
    const summary = reviewReadinessSummaryForChapter(c.officialChapterId);
    return `## Review state — Class 6, ${c.title}

${summary.headline}

- Complete drafts: **${summary.completeDrafts}**
- Review-ready: **${summary.reviewReady}**
- Awaiting package preparation: **${summary.awaitingPackagePreparation}**
- Sent: **${summary.reviewSent}** · Received: **${summary.reviewReceived}**`;
  })
  .join('\n\n')}

Nothing in either chapter is waiting on engineering. The remaining step
is a person reading a package.
`;
}

// ---------------------------------------------------------------------------

export function renderStructureVerificationBacklog(version: string): string {
  return renderStructureBacklogDocument(version);
}


// ---------------------------------------------------------------------------
// v0.78 §A1-§A4 — THE SOURCE INVENTORY, GENERATED.
// ---------------------------------------------------------------------------
//
// THE CONTRADICTION THIS RESOLVES, AND WHOSE FAULT IT WAS
//
// v0.77.3 shipped four documents disagreeing about Classes 9-12. The
// registry marked them `primary_source_verified` with a CBSE source URL,
// an inspection date and an evidence note. The generated coverage matrix
// and structure backlog agreed with the registry. Two files did not:
// `CURRENT_MATH_BOOKS_CLASSES_1_12.md` said "not verified / unknown",
// and the release report said "Verified classes: Class 6 only".
//
// Both of those were mine, and both were wrong for the same reason: I
// hand-wrote an evidence inventory from what I happened to remember
// instead of reading the registry. The registry was right the whole
// time. That is precisely why an evidence inventory must not be
// hand-maintained — a hand-written file about machine-held facts drifts
// the moment anyone's memory is incomplete.
//
// SYLLABUS VERIFIED IS NOT TEXTBOOK VERIFIED (§A3)
//
// The registry already models the distinction and this document must not
// flatten it:
//
//   topLevel 'chapter'        a textbook contents page was read. Class 6.
//   topLevel 'unit'           a syllabus organised into units was read.
//                             Classes 9-12.
//   chaptersEstablished       the syllabus PRINTS a chapter-name column.
//                             True for Class 9 only; Class 10's topic
//                             titles resemble NCERT chapter names, and
//                             resembling is not evidence.
//   topicsKnown               the source enumerates sub-topics. An empty
//                             topic list with topicsKnown true means the
//                             source lists none — different from not
//                             having looked.



export function renderSourceInventory(version: string): string {
  return renderBooksDocument(version);
}

