// ===========================================================================
// v0.78 §A1-§A3 — CURRENT-STATE DOCUMENTS, GENERATED.
//
// THE DEFECT THIS FIXES
//
// The packaged v0.77.2 tree shipped `CONTENT_BACKLOG.md` and
// `CURRICULUM_COVERAGE_MATRIX.md` still stamped v0.72.0 and still saying
// "8 of 9 Fractions sections complete, §7.9 incomplete". The code had
// said 9 of 9 since v0.75. Both files carried the line "Generated by
// coverageBacklog() … Not maintained by hand", which was true when they
// were written and became a lie the moment the model moved: nothing
// regenerated them and nothing checked them.
//
// A document that claims to be generated and is not is worse than one
// admitting it is hand-written, because a reader has no reason to doubt
// it. Someone planning content from that backlog would have planned to
// write a section that already existed.
//
// THE FIX HAS TWO HALVES, AND THE SECOND IS THE IMPORTANT ONE
//
//   1. these render functions read the live model, so regenerating is
//      one command;
//   2. `v078StateDocs.test.ts` asserts the bytes on disk equal what
//      these functions produce right now. Staleness is a test failure,
//      not something to be noticed.
//
// Regenerate with:  PRAGATI_EMIT_DOCS=1 npx vitest run v078StateDocs
//
// WHAT THESE DOCUMENTS MUST KEEP SEPARATE
//
// The three truths never collapse into one number:
//   CURRICULUM      what the official book contains;
//   INSTRUCTION     what Pragati has written for it;
//   REVIEW          what an educator has approved and what is published.
// A chapter can be fully represented, entirely unwritten, and correctly
// show zero published lessons — all three at once, all three true.
// ===========================================================================

import {
  coverageMatrix,
  coverageBacklog,
  backlogSummary,
  type GradeCoverageRow,
} from './coverageMatrix';
// v0.82.3 §3 — state documents made product-wide claims out of a
// deprecated Fractions-only wrapper, so every "current state" sentence
// silently meant Chapter 7.
import {
  reviewReadinessByChapter,
  reviewReadinessSummaryForChapter,
} from './reviewReadiness';
import { AUTHORED_CHAPTERS } from './authoredSections';
import { assessSection } from './instructionalCompleteness';
import {
  officialCurriculumForGrade,
  OFFICIAL_CURRICULA,
  type OfficialCurriculum,
} from './officialCurriculum';

const STAMP = (version: string) =>
  `**Generated** from the live model by \`src/curriculum/stateDocs.ts\` at ` +
  `version ${version}. Do not hand-edit: \`v078StateDocs.test.ts\` compares ` +
  `this file to the model on every run, so an edit here fails the suite and ` +
  `a model change that is not regenerated fails it too.`;

function table(headers: string[], rows: string[][]): string {
  const head = `| ${headers.join(' | ')} |`;
  const rule = `|${headers.map(() => '---').join('|')}|`;
  const body = rows.map((r) => `| ${r.join(' | ')} |`).join('\n');
  return [head, rule, body].join('\n');
}

const n = (v: number | null) => (v === null ? '—' : String(v));

// ---------------------------------------------------------------------------


/**
 * v0.82.3 §1/§2 — chapter distribution, derived.
 *
 * The matrix said "12 complete instructional drafts, all in Class 6
 * Chapter 7", which stopped being true the moment Number Play was
 * authored — and would have gone on being printed as fact. The
 * breakdown is computed from the authored registry, so a chapter added
 * later appears here without anyone remembering to edit a sentence.
 */
function authoredChapterBreakdown(): Array<{
  title: string;
  complete: number;
  reviewReady: number;
}> {
  return AUTHORED_CHAPTERS.map((c) => {
    const sections = c.sections();
    return {
      title: c.title,
      complete: sections.filter(
        (s) => assessSection(s).level === 'complete_instructional_draft'
      ).length,
      reviewReady: reviewReadinessSummaryForChapter(c.officialChapterId)
        .reviewReady,
    };
  });
}

function breakdownSentence(): string {
  const parts = authoredChapterBreakdown()
    .filter((c) => c.complete > 0)
    .map((c) => `${c.complete} in ${c.title}`);
  const total = authoredChapterBreakdown().reduce((a, c) => a + c.complete, 0);
  return `${total} complete instructional drafts — ${parts.join(', ')}`;
}

export function renderCoverageMatrix(version: string): string {
  const rows = coverageMatrix();
  const rr = reviewReadinessSummaryForChapter(AUTHORED_CHAPTERS[1].officialChapterId);
  const verified = rows.filter((r) => r.verified);
  const unverified = rows.filter((r) => !r.verified);

  return `# Curriculum Coverage Matrix — Classes 1–12 Mathematics

${STAMP(version)}

---

## The three truths, kept apart

| Truth | Question it answers | Current answer |
|---|---|---|
| Curriculum completeness | Does Pragati represent every official record for a verified class? | ${verified.length} of 12 classes primary-source verified; ${verified.reduce((a, r) => a + (r.omissions ?? 0), 0)} omissions across them |
| Instructional completeness | Has Pragati written the teaching for those records? | ${breakdownSentence()} |
| Review / publication | Has an educator approved it, and is it published? | ${rows.reduce((a, r) => a + r.educatorReviewed, 0)} reviewed, ${rows.reduce((a, r) => a + r.published, 0)} published |

An unverified class is **not** a class with no curriculum. It is a class
whose curriculum Pragati has not yet confirmed against a primary source,
and its denominator is unknown rather than zero.

---

## 1. Curriculum completeness

${table(
  // v0.82.4 §3 — four hierarchy columns, because the sources do not
  // share one. A dash means the source does not define that level, not
  // that we failed to count it.
  ['Class', 'Primary verified', 'Source', 'Units', 'Chapters', 'Sections', 'Topics', 'Records represented', 'Omissions'],
  rows.map((r) => [
    r.gradeLabel,
    r.verified ? 'yes' : 'not yet',
    r.source ?? '—',
    n(r.officialUnits),
    n(r.officialChapters),
    n(r.officialSections),
    n(r.officialTopics),
    n(r.recordsRepresented),
    n(r.omissions),
  ])
)}

## 2. Instructional content completeness

${table(
  // v0.82.5 §5 — "Topics: Learn" called Class 6's authored records
  // topics, and they are sections. These counts are per authored
  // RECORD, whatever level the source calls it, so the labels say so.
  // The values are unchanged; only the words were wrong.
  ['Class', 'Student-openable Learn chapters', 'Records with Learn', 'Records with guided practice', 'Records with independent practice', 'Records with reasoning', 'Records with a visual', 'Records with teacher notes', 'Complete drafts'],
  rows.map((r) => [
    r.gradeLabel,
    String(r.chaptersWithLearn),
    String(r.topicsWithLearn),
    String(r.topicsWithGuidedPractice),
    String(r.topicsWithIndependentPractice),
    String(r.topicsWithReasoning),
    String(r.topicsWithVisual),
    String(r.topicsWithTeacherResources),
    String(r.completeInstructionalDrafts),
  ])
)}

## 3. Review and publication

${table(
  ['Class', 'Drafts', 'Educator reviewed', 'Student ready', 'Published'],
  rows.map((r) => [
    r.gradeLabel,
    String(r.drafts),
    String(r.educatorReviewed),
    String(r.studentReady),
    String(r.published),
  ])
)}

### Review readiness, Class 6 Chapter 7

- Complete drafts: **${rr.completeDrafts}**
- Review-ready (blocked on a person): **${rr.reviewReady}**
- Awaiting package preparation (blocked on engineering): **${rr.awaitingPackagePreparation}**
- Sent: **${rr.reviewSent}** · Received: **${rr.reviewReceived}** · Adjudicated: **${rr.reviewAdjudicated}**

${rr.headline}

---

## The five states a section can be in

v0.74 §5 established these, and they stay stated separately because
collapsing any two of them is how a draft starts looking like a lesson.

1. **No instructional content at all** — the official record exists in
   Pragati and nothing has been written for it.
2. **Partial draft** — some of Learn, practice, reasoning or teacher
   notes exists, but not enough to be reviewable.
3. **Complete draft, no review package** — reviewable in substance, but
   an educator cannot yet read it because the package is unbuilt. This
   is engineering work.
4. **Complete draft, review-ready** — blocked on a person, not on us.
5. **Reviewed and published** — the only state a student may see.

Currently, by chapter:

${table(
  ['Chapter', 'Complete drafts', 'Review-ready (state 4)'],
  authoredChapterBreakdown().map((c) => [
    c.title,
    String(c.complete),
    String(c.reviewReady),
  ])
)}

**Total: ${authoredChapterBreakdown().reduce((a, c) => a + c.reviewReady, 0)}**
sections in state 4, **0** in state 3, and **0** in state 5.

The packages stay chapter-scoped — a reviewer receives one chapter — so
this total is a report, not a queue.

---

## Backlog totals mean the verified classes only

The known instructional backlog is the work Pragati can currently see.
It is **not the Classes 1–12 workload**: classes awaiting primary
verification have an unknown denominator, and adding zero for them would
understate the real total by an unknown amount.

---

## Classes awaiting primary verification

${unverified.length === 0 ? 'None.' : unverified.map((r) => `- ${r.gradeLabel}`).join('\n')}

For these classes every count above is unknown, not zero. They are
tracked in \`STRUCTURE_VERIFICATION_BACKLOG.md\`.
`;
}

// ---------------------------------------------------------------------------

export function renderContentBacklog(version: string): string {
  const entries = coverageBacklog();
  const s = backlogSummary();
  // Read from the same matrix everything else reads, so the backlog and
  // the coverage document cannot disagree about which classes are
  // verified.
  const unverified = coverageMatrix().filter((r) => !r.verified);

  return `# Content Backlog — what is missing, and in what order

${STAMP(version)}

---

## Headline, stated honestly

**Known instructional backlog: ${s.total} records.**

That figure covers only classes whose curriculum has been verified
against a primary source. **${unverified.length} of 12 classes are not
yet verified**, so their backlog is *unknown*, not zero — see §33 of the
v0.78 brief and \`STRUCTURE_VERIFICATION_BACKLOG.md\`. Any statement of
the form "Pragati has N items of work left" that quotes only the number
above is wrong by an unknown margin.

| | |
|---|---|
| Known backlog records | ${s.total} |
| Missing Learn | ${s.learnMissing} |
| Missing practice | ${s.practiceMissing} |
| Needing review | ${s.reviewNeed} |
| P1 / P2 / P3 | ${s.byPriority.P1} / ${s.byPriority.P2} / ${s.byPriority.P3} |
| Classes with unknown denominator | ${unverified.length} |

## By class

${table(
  ['Class', 'Known backlog records'],
  Object.entries(s.byGrade).map(([g, c]) => [g, String(c)])
)}

${reviewReadinessByChapter()
  .filter((c) => c.rows.length > 0)
  .map((c) => {
    const summary = reviewReadinessSummaryForChapter(c.officialChapterId);
    return `## Review state — Class 6, ${c.title}

${summary.headline}

- Complete drafts: **${summary.completeDrafts}**
- Review-ready: **${summary.reviewReady}**
- Awaiting package preparation: **${summary.awaitingPackagePreparation}**
- Sent: **${summary.reviewSent}** · Received: **${summary.reviewReceived}**`;
  })
  .join('\n\n')}

Nothing in either chapter is waiting on engineering. The remaining step
is a person reading a package.

## The records

${
  entries.length === 0
    ? 'No known backlog records.'
    : table(
        ['Priority', 'Class', 'Chapter', 'Section', 'Learn', 'Practice', 'Review'],
        entries
          .slice(0, 200)
          .map((e) => [
            e.priority,
            e.gradeLabel,
            e.officialUnitTitle,
            e.officialSectionTitle ?? '(whole unit — no verified section depth)',
            e.learnMissing ? 'missing' : 'present',
            e.practiceMissing ? 'missing' : 'present',
            e.reviewNeed ? 'needed' : '—',
          ])
      )
}
${entries.length > 200 ? `\n_${entries.length - 200} further records omitted from this table; the full set is in the model._\n` : ''}`;
}

// ---------------------------------------------------------------------------

export function renderStructureVerificationBacklog(version: string): string {
  const rows: GradeCoverageRow[] = coverageMatrix();
  const unverified = rows.filter((r) => !r.verified);

  return `# Structure Verification Backlog — classes awaiting primary evidence

${STAMP(version)}

---

**${unverified.length} of 12 classes have no primary-source-verified
curriculum in Pragati.**

For each, the official book almost certainly exists and Pragati simply
has not confirmed its structure against a primary source. Until it does,
the number of units, chapters and topics for that class is **unknown**.
Recording it as zero would let an unverified class look complete.

${table(
  ['Class', 'Units', 'Chapters', 'Sections', 'Topics', 'Status'],
  unverified.map((r) => [
    r.gradeLabel,
    n(r.officialUnits),
    n(r.officialChapters),
    n(r.officialSections),
    n(r.officialTopics),
    'awaiting primary source verification',
  ])
)}

## Verified classes, for contrast

${table(
  // v0.82.5 §6 — found by the bounded audit. This table had no Sections
  // column, so once v0.82.4 correctly stopped reporting Class 6's 65 as
  // topics they vanished from it entirely: a verified count silently
  // dropped from a document about verification.
  ['Class', 'Source', 'Units', 'Chapters', 'Sections', 'Topics'],
  rows
    .filter((r) => r.verified)
    .map((r) => [
      r.gradeLabel,
      r.source ?? '—',
      n(r.officialUnits),
      n(r.officialChapters),
      n(r.officialSections),
      n(r.officialTopics),
    ])
)}
`;
}

// ---------------------------------------------------------------------------
// v0.78 §A1-§A4 — THE SOURCE INVENTORY, GENERATED.
// ---------------------------------------------------------------------------
//
// THE CONTRADICTION THIS RESOLVES, AND WHOSE FAULT IT WAS
//
// v0.77.3 shipped four documents disagreeing about Classes 9-12. The
// registry marked them `primary_source_verified` with a CBSE source URL,
// an inspection date and an evidence note. The generated coverage matrix
// and structure backlog agreed with the registry. Two files did not:
// `CURRENT_MATH_BOOKS_CLASSES_1_12.md` said "not verified / unknown",
// and the release report said "Verified classes: Class 6 only".
//
// Both of those were mine, and both were wrong for the same reason: I
// hand-wrote an evidence inventory from what I happened to remember
// instead of reading the registry. The registry was right the whole
// time. That is precisely why an evidence inventory must not be
// hand-maintained — a hand-written file about machine-held facts drifts
// the moment anyone's memory is incomplete.
//
// SYLLABUS VERIFIED IS NOT TEXTBOOK VERIFIED (§A3)
//
// The registry already models the distinction and this document must not
// flatten it:
//
//   topLevel 'chapter'        a textbook contents page was read. Class 6.
//   topLevel 'unit'           a syllabus organised into units was read.
//                             Classes 9-12.
//   chaptersEstablished       the syllabus PRINTS a chapter-name column.
//                             True for Class 9 only; Class 10's topic
//                             titles resemble NCERT chapter names, and
//                             resembling is not evidence.
//   topicsKnown               the source enumerates sub-topics. An empty
//                             topic list with topicsKnown true means the
//                             source lists none — different from not
//                             having looked.

/**
 * Chapters a syllabus actually names, rather than a count inferred from
 * its topics. Classes 10-12 print no chapter column; their topic titles
 * resemble NCERT chapter names and resembling is not evidence.
 */
function chapterNamesFrom(c: OfficialCurriculum | null | undefined): string {
  if (!c) return '—';
  const named = c.units.reduce(
    (a, u) => a + (u.chaptersEstablished ? u.chapters.length : 0),
    0
  );
  return named > 0 ? String(named) : '—';
}

function depthOf(grade: Parameters<typeof officialCurriculumForGrade>[0]): string {
  const c = officialCurriculumForGrade(grade);
  if (!c || c.status !== 'primary_source_verified') return 'not verified';
  if (c.topLevel === 'chapter') return 'textbook chapters read from source';
  const withChapters = c.units.filter((u) => u.chaptersEstablished).length;
  return withChapters > 0
    ? `syllabus units verified; chapter names printed by the source for ${withChapters} of ${c.units.length} units`
    : 'syllabus units and topics verified; textbook chapter denominator NOT verified';
}

export function renderSourceInventory(version: string): string {
  const rows = coverageMatrix();
  return `# Current Mathematics sources, Classes 1–12

${STAMP(version)}

This document exists because a hand-written version of it contradicted
the registry in v0.77.3. It is now derived from the same records the
product reads, so it cannot disagree with them.

## Two separate questions

**Book identity** — do we know which book this is? **Structure** — have
we read what is in it? They are answered by different evidence and are
recorded separately. A title carried by agreeing secondary sources is
\`secondary_discovery_only\`: a usable lead, not an established fact.
v0.51 is why — secondary sources agreed about Class 6 and disagreed
about Class 7, and agreement felt like confirmation both times.

## Verification depth is not one thing

A CBSE syllabus can primary-verify units and named topics without
proving anything about NCERT textbook chapter structure. The two are
recorded separately below and must never be collapsed.

${table(
  ['Class', 'Book identity', 'Structure', 'Document', 'Authority', 'Year', 'Inspected', 'Top level', 'Units', 'Chapters', 'Sections', 'Topics', 'Verification depth'],
  rows.map((r) => {
    const c = officialCurriculumForGrade(r.grade);
    return [
      r.gradeLabel,
      c?.bookIdentityStatus ?? 'unverified',
      c?.structureVerificationStatus ?? 'pending_verification',
      c?.documentTitle ?? 'unknown',
      c?.authority ?? '—',
      c?.academicYear ?? '—',
      c?.inspectionDate ?? '—',
      c?.topLevel ?? '—',
      // §2 — Ganita Prakash defines chapters and sections and no unit
      // layer above them. Printing "Units 10 / Chapters 10" invents a
      // hierarchy the book does not have and makes two unlike
      // structures look equivalent. Where the source's top level IS the
      // chapter, the unit column is empty.
      n(r.officialUnits),
      c?.topLevel === 'chapter' ? n(r.officialChapters) : chapterNamesFrom(c),
      // v0.82.5 §1 — this was `officialSections ?? officialTopics` in one
      // cell under a "Topics" header, so Class 6's 65 sections were
      // printed as topics. Two levels, two cells.
      n(r.officialSections),
      n(r.officialTopics),
      depthOf(r.grade),
    ];
  })
)}

## Evidence notes, verbatim

${OFFICIAL_CURRICULA.filter((c: OfficialCurriculum) => c.status === 'primary_source_verified')
  .map(
    (c: OfficialCurriculum) =>
      `### ${c.grade} — ${c.documentTitle}\n\n- Source: ${c.sourceUrl ?? '—'}\n- Inspected: ${c.inspectionDate ?? '—'}\n\n${c.evidenceNote}`
  )
  .join('\n\n')}

## Still unverified

${rows.filter((r) => !r.verified).map((r) => `- ${r.gradeLabel}`).join('\n')}

For these the denominator is **unknown, not zero**.
`;
}
